on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

name: Windows build
jobs:
    test-windows:
        runs-on: windows-latest
        strategy:
            matrix:
                python-version: ["3.12"]

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  version: "0.4.16"
                  enable-cache: false

            - name: Install dependencies
              run: |
                  uv venv --python ${{ matrix.python-version }}
                  uv pip install .

            - name: Test import
              run: |
                  uv run python -c "import geoai; print('geoai import successful')"
